title: Eric L Sammons # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Manager 
  <br><br>
  <a href="https://www.linkedin.com/in/elsammons/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://public.tableau.com/app/profile/eric.l.sammons">Tableau Public</a>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
